name: Run tests and deploy

on: push

jobs:
  run-tests:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        # Specify some input for this particular action
        with:
          python-version: '3.10.7'
      - name: Install Dependencies
        run: pip install -r requirements.txt
      - name: Run tests
        run: pytest==7.1.3

  deploy:
      needs: run-tests
      runs-on: ubuntu-latest
      steps:
        - name: SSH Remote Commands
          uses: appleboy/ssh-action@v0.1.4
          with:
            host: ${{ secrets.HOST }}
            username: ${{ secrets.USERNAME }}
            key: ${{ secrets.KEY }}
            port: ${{ secrets.PORT }}
            script: |
              echo 'Here is some code'
              cd /home/cd-project/
              echo 'Bash is just a programming language, really.'
              git pull
              systemctl restart my-application
