name: run tests

on: push

jobs:
  run-tests:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        # Specify some input for this particular action
        with:
          python-version: '3.10.7'
      - name: Install Dependencies
        run: pip install -r requirements.txt
      - name: Run tests
        run: pytest==7.1.3
